service: unicorn

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: ap-southeast-2

plugins:
  - serverless-python-requirements
  - serverless-ssm-fetch

package:
  exclude:
    - requirements.txt
    - README.md
    - .gitignore

custom:
  serverlessSsmFetch:
      DB_NAME: /variables/lambda/db_name~true
      PASSWORD: /variables/lambda/password~true
      USERNAME: /variables/lambda/username~true
      HOST_NAME: /variables/lambda/host_name~true

functions:
  get_parameter:
    handler: get_parameter.handler
    ssmToEnvironment:
     - HOST_NAME
    events:
      - http:
          path: /
          method: get
    vpc:
      securityGroupIds:
        - sg-96ae5fe8
      subnetIds:
        - subnet-e769e1bf
        - subnet-82b3b8cb
        - subnet-4f140d28

  sqli_vulnerable:
    handler: handler.sqli_vulnerable
    events:
      - http:
          path: /sqli_vuln
          method: get
    vpc:
      securityGroupIds:
        - sg-96ae5fe8
      subnetIds:
        - subnet-e769e1bf
        - subnet-82b3b8cb
        - subnet-4f140d28
  sqli_secure:
    handler: handler.sqli_secure
    events:
      - http:
          path: /sqli_secure
          method: get
    vpc:
      securityGroupIds:
        - sg-96ae5fe8
      subnetIds:
        - subnet-e769e1bf
        - subnet-82b3b8cb
        - subnet-4f140d28
  jwt_insecure:
    handler: handler.jwt_insecure
    events:
      - http:
          path: /jwt_insecure
          method: get
    vpc:
      securityGroupIds:
        - sg-96ae5fe8
      subnetIds:
        - subnet-e769e1bf
        - subnet-82b3b8cb
        - subnet-4f140d28
